// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StreetBroker.Models;

namespace StreetBroker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200422111522_StreetBroker-v1.1")]
    partial class StreetBrokerv11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("StreetBroker.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnName("address")
                        .HasColumnType("character varying(700)")
                        .HasMaxLength(700);

                    b.Property<string>("City")
                        .HasColumnName("city")
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Country")
                        .HasColumnName("country")
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnName("create_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("first_name")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Gender")
                        .HasColumnName("gender")
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("last_name")
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnName("phone_number")
                        .HasColumnType("text");

                    b.Property<byte>("RecordStatus")
                        .HasColumnName("record_status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnName("update_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Zip")
                        .HasColumnName("zip")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("customer","cor");
                });

            modelBuilder.Entity("StreetBroker.Models.Dealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnName("create_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("first_name")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("LastName")
                        .HasColumnName("last_name")
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnName("phone_number")
                        .HasColumnType("text");

                    b.Property<byte>("RecordStatus")
                        .HasColumnName("record_status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnName("update_date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("dealer","cor");
                });

            modelBuilder.Entity("StreetBroker.Models.RepoOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnName("amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnName("create_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnName("customer_id")
                        .HasColumnType("bigint");

                    b.Property<long>("DealerId")
                        .HasColumnName("dealer_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("GrossInterestAmount")
                        .HasColumnName("gross_interest_amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("GrossInterestRate")
                        .HasColumnName("gross_interest_rate")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnName("net_interest_rate")
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("Maturity")
                        .HasColumnName("maturity")
                        .HasColumnType("Date");

                    b.Property<decimal>("NetInterestAmount")
                        .HasColumnName("net_interest_amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<byte>("OrderStatus")
                        .HasColumnName("order_status")
                        .HasColumnType("smallint");

                    b.Property<byte>("RecordStatus")
                        .HasColumnName("record_status")
                        .HasColumnType("smallint");

                    b.Property<decimal>("ReturnGrossInterestAmount")
                        .HasColumnName("return_gross_interest_amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ReturnNetInterestAmount")
                        .HasColumnName("return_net_interest_amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("start_date")
                        .HasColumnType("Date");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnName("tax_amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnName("update_date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("repo_order","repo");
                });
#pragma warning restore 612, 618
        }
    }
}
